parameters: 
- name: obligationCheckerBranch
  displayName: 'ObligationChecker branch:'
  type: string

stages:
- stage: Test
  jobs: 
  - job: 
    steps:
    - task: Bash@3
      displayName: 'Obligation build test'
      inputs:
        targetType: 'inline'
        script: |
            echo 'buidling obligation frontend on ${{parameters.obligationCheckerBranch}}'
             
