parameters: 
- name: obligationCheckerBranch
  displayName: 'ObligationChecker branch:'
  type: string

stages:
- stage: Test
  jobs: 
  - job: 
    steps:
    - bash: |
            echo variable: ${{parameters.obligationCheckerBranch}}

     
             
