parameters:
  - name: runTests
    displayName: Run tests
    type: boolean
    default: true
  - name: sonarqubeInstance
    displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
    type: string
    default: 'SonarQube'
    values:
    - 'SonarQube'
    - 'SonarQubeLatest'
  - name: obligationCheckerBranch
    displayName: 'ObligationChecker branch:'
    type: string
  - name: checkoutName
    type: string
    
stages:
  - template: epr-build-pipeline.yaml@CommonTemplates
    parameters:
     solutionFolder: $(solutionFolder)
     projectFolder: $(ocf-projectFolder)
     testProjectFolder: $(ocf-testProjectFolder)
     sonarQubeProjectKey: $(ocf-sonarQubeProjectKey)
     sonarQubeProjectName: $(ocf-sonarQubeProjectName)
     runTests: ${{ parameters.runTests }}
     azureSubscription: $(azureSubscription)
     acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
     acrRepositoryName: $(ocf-acr.repositoryName)
     branchName: ${{ parameters.obligationcheckerBranch }}
     runNugetTasks: false
     serviceName: $(ocf-serviceName)
     sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
     checkoutName: ${{ parameters.checkoutName }}


     
             
