variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'obligationregistry'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'obligationregistry'
  serviceName: 'prdrwdwebwa1401'